config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  get 'logout', to: 'sessions#destroy'
  get 'bag', to: 'products#bag'
  get 'harness', to: 'products#harness'
  get '/auth/facebook/callback', to: 'sessions#omni'
  get '/auth/google_oauth2/callback', to: 'sessions#omni'
  
  resources :users
  resources :po_products
  resources :product_materials
  resources :materials
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :purchase_orders do 
    resources :po_products
  end
  
  resources :products do 
    resources :product_materials
  end
  


end

app/models/po_product.rb
class PoProduct < ApplicationRecord
  belongs_to :purchase_order, optional: true
  belongs_to :product, optional: true
  validates :quantity, presence: true

  scope :most_recent, -> {PoProduct.order("created_at DESC").limit(5)}
  # scope :order_by_quantity, -> {order(:quantity)}
end

app/controllers/po_products_controller.rb
class PoProductsController < ApplicationController
    before_action :logged_in?
    before_action :set_po_product, only: [:show, :edit, :update, :destroy]
    before_action :edit_or_delete, only: [:edit, :update, :destroy]
       
    def index
        if params[:purchase_order_id] && @purchase_order = PurchaseOrder.find_by(id: params[:purchase_order_id])
            @po_products = @purchase_order.po_products
        else
            @po_products = PoProduct.all.most_recent
        end
    end

    def new
        @po_product = PoProduct.new(purchase_order_id: params[:purchase_order_id])
    end
    
    def create
        @po_product = PoProduct.new(po_product_params)
        if @po_product.save!
            redirect_to purchase_orders_path(@po_product.purchase_order)
        else
            render :new
        end
    end

    def show 
    end

    def edit 
    end

    def update 
        if @po_product.update(po_product_params)
            redirect_to purchase_order_po_products_path(@po_product)
        else 
            render :new
        end
    end

    def destroy
        @po_product.destroy 
        redirect_to root_path
    end

    private 
    def po_product_params
        params.require(:po_product).permit(:quantity, :product_id, :purchase_order_id, purchase_order_attributes: [:po, :bin, :start_date, :completion_date])
    end

    def set_po_product
        @po_product = PoProduct.find_by(id: params[:id])
        if !@po_product
            redirect_to po_products_path
        end
    end

    def edit_or_delete
        set_po_product
        redirect_to po_products_path, alert: "Editing permissions denied" unless !!authorized
    end

    def authorized
        helpers.current_user == @po_product.product.user
     end
end

app/helpers/po_products_helper.rb
module PoProductsHelper
end

app/views/po_products/_form.html.erb
<h3 class="login-heading mb-4">New Purchase Order Product</h3>
<%= render partial: 'shared/errors', locals: {model: @po_product} %>
<%= render partial: 'shared/flash_errors', locals: {model: @po_product} %>
<br>
<%= form_for @po_product do |f| %>
    <%= f.number_field :quantity, placeholder: "Quantity", required: true, class: "form-control", autofocus: true %><br>
    <%= f.collection_select :product_id, Product.all, :id, :name, prompt: "Product" %><br><br>
    <%= f.collection_select :purchase_order_id, PurchaseOrder.all, :id, :po, prompt: "Purchase Order" %>
    <!--<br><br>
    <% if !params[:purchase_order_id] %>
        <h4>Or add a new purchase order:</h4>

        <%= f.fields_for :purchase_order do |po|%>
            <%= po.text_field :po, placeholder: "Order Number" %><br>
            <%= po.text_field :bin, placeholder: "BIN" %><br>
            <%= po.text_field :start_date, placeholder: "Start Date" %><br>
            <%= po.text_field :completion_date, placeholder: "Exit Date" %><br>
        <% end %>
    <% end %>-->
        <hr>
    <% if current_page?(new_po_product_path) %>
        <%= f.button "Assign Product to P.O.", class: "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" %>
    <% else %>
        <%= f.button "Update Purchase Order Product", class: "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" %>
    <% end %>
    <hr>
    Dont't see product or purchase order?
    <hr>
    <%= link_to "Create Product", new_product_path, class: "btn btn-primary" %> OR 
    <%= link_to "Create Purchase Order", new_purchase_order_path, class: "btn btn-primary" %><hr>
    <%= link_to "Back", :back, class: "btn btn-primary" %>&nbsp;&nbsp;&nbsp;
    <% if controller.action_name == 'edit' %>
        <%= link_to "Delete", po_product_path(@po_product), method: :delete, class: "btn btn-primary",data: {confirm: "Are you sure?"} %>
    <% end %>
<% end %>

app/views/po_products/index.html.erb
<% if @purchase_order %>
    <h2 class="po-index-heading mb-4">Product of Purchase Order # <%= @purchase_order.try(:po) %></h2>
<% else %>
    <h2 class="po-index-heading mb-4">Purchase Order Products</h2>
<% end %>
<%= render partial: 'shared/flash_errors', locals: {model: @po_product} %>


<table>
    <tr>
        <th>Name</th>
        <th>Color</th>
        <th>Size</th>
        <th>SKU</th>
        <th>Category</th>
        <th>Quantity</th>
        <% @po_products.each do |p| %>
    </tr>
        <td><%= button_to p.product.name, purchase_order_path(p.purchase_order), method: :get %></td>
        <td><%= p.product.color.titlecase %></td>
        <td><%= p.product.size.upcase %></td>
        <td><%= p.product.sku %></td>
        <td><%= p.product.category.titlecase %></td>
        <td><%= button_to p.quantity, edit_purchase_order_po_product_path(p.purchase_order, p), method: :get %></td>
    </tr>
        <% end %>
</table>
<hr>
<%= link_to "Back", :back, class: "btn btn-primary" %>

app/views/po_products/show.html.erb
<h3 class="login-heading mb-4"><%= @po_product.product.name %></h3>
<%= render partial: 'shared/errors', locals: {model: @po_product} %>
<%= render partial: 'shared/flash_errors', locals: {model: @po_product} %>
<table>
    <tr>
        <th>Quantity</th>
    </tr>
        <td><%= @po_product.quantity %></td>
    </tr>
</table>
<hr>
<%= link_to "Edit", edit_po_product_path(@po_product), class: "btn btn-primary" %>&nbsp;&nbsp;&nbsp; OR &nbsp;&nbsp;&nbsp;
<%= link_to "Delete", po_product_path(@po_product), method: :delete, class: "btn btn-primary",data: {confirm: "Are you sure?"} %><hr>
<%= link_to "Back", :back, class: "btn btn-primary" %>