config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  get 'logout', to: 'sessions#destroy'
  get 'bag', to: 'products#bag'
  get 'harness', to: 'products#harness'
  get '/auth/facebook/callback', to: 'sessions#omni'
  get '/auth/google_oauth2/callback', to: 'sessions#omni'
  
  resources :users
  resources :po_products
  resources :product_materials
  resources :materials
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :purchase_orders do 
    resources :po_products
  end
  
  resources :products do 
    resources :product_materials
  end
  


end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
    belongs_to :user

    has_many :po_products
    has_many :products, through: :po_products
    
    validates :po, :bin, :start_date, :completion_date, presence: true
    validates :po, :bin, uniqueness: true

    private 

    def title_case_bin
        self.bin = bin.uppercase
    end

end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
    before_action :logged_in?
    before_action :logged_in?, only: [:edit, :destroy]
    before_action :set_po, only: [:show, :edit, :update, :destroy]
    def index 
        @purchase_orders = PurchaseOrder.all
    end

    def new
        @purchase_order = PurchaseOrder.new
    end
    
    def create
        @purchase_order = helpers.current_user.purchase_orders.build(po_params)
        if @purchase_order.save
            redirect_to purchase_orders_path
        else 
            render :new
        end
    end

    def show
        
    end

    def edit 

    end

    def update
        if @purchase_order.update(po_params)
            redirect_to purchase_orders_path(@purchase_order)
        else
            render :new
        end
    end

    def destroy 
        @purchase_order.destroy 
        redirect_to purchase_orders_path
    end

    private 
    def po_params
        params.require(:purchase_order).permit(:po, :bin, :start_date, :completion_date)
    end

    def set_po
        @purchase_order = PurchaseOrder.find_by(id: params[:id])
        if !@purchase_order
            redirect_to purchase_orders_path
        end
    end

    def edit_or_delete
        set_po_purchase_order
        redirect_to purchase_orders_path, alert: "Editing permissions denied" unless !!authorized
    end

    def authorized
        helpers.current_user == @purchase_order.user
     end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/purchase_orders/_form.html.erb
<h3 class="login-heading mb-4">New Purchase Order</h3>
<%= render partial: 'shared/errors', locals: {model: @purchase_order} %>
<%= render partial: 'shared/flash_errors', locals: {model: @purchase_order} %>

<br>
<%= form_for @purchase_order do |f| %>
    <%= f.text_field :po, placeholder: "Purchase Order", required: true, class: "form-control", autofocus: true %><br>
    <%= f.text_field :bin, placeholder: "BIN", required: true, class: "form-control" %><br>
    <%= f.text_field :start_date, placeholder: "Start Date - MM/DD/YYYY", required: true, class: "form-control" %><br>
    <%= f.text_field :completion_date, placeholder: "Exit Date - MM/DD/YYYY", required: true, class: "form-control" %><br><hr>
    <%= f.button class: "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" %>
<% end %>
            

app/views/purchase_orders/edit.html.erb
<%= render "form" %>

app/views/purchase_orders/index.html.erb
<h2 class="po-index-heading mb-4">All Purchase Orders!</h2>    
<%= render partial: 'shared/flash_errors', locals: {model: @purchase_order} %>
<table>
    <tr>
        <th>P.O. Number</th>
        <th>BIN</th>
        <th>Start Date</th>
        <th>Exit Date</th>
        <% @purchase_orders.each do |po| %>
    </tr>
        <td><%= button_to po.po, purchase_order_path(po), method: :get %></td>
        <td><%= po.bin %></td>
        <td><%= po.start_date %></td>
        <td><%= po.completion_date %></td>
    </tr>
        <% end %>
</table>
<br>
<%= link_to "New Purchase Order", new_purchase_order_path, class: "btn btn-primary" %><hr>
<%= link_to "Back", :back, class: "btn btn-primary" %>

app/views/purchase_orders/show.html.erb
<table>
    <tr>
        <th>P.O. Number</th>
        <th>BIN</th>
        <th>Start Date</th>
        <th>Exit Date</th>
    </tr>
        <td><%= @purchase_order.po %></td>
        <td><%= @purchase_order.bin %></td>
        <td><%= @purchase_order.start_date %></td>
        <td><%= @purchase_order.completion_date %></td>
    </tr>
</table>
<hr>
<%= link_to "More Info...", purchase_order_po_products_path(@purchase_order), class: "btn btn-primary" %>&nbsp;&nbsp;&nbsp;
<%= link_to "Edit", edit_purchase_order_path(@purchase_order), class: "btn btn-primary" %>&nbsp;&nbsp;&nbsp;
<%= link_to "Delete", purchase_order_path(@purchase_order), method: :delete, class: "btn btn-primary",data: {confirm: "Are you sure?"} %><br><br>
<%= link_to "Add Product to Purchase Order", new_purchase_order_po_product_path(@purchase_order), class: "btn btn-primary" %><hr>
<%= link_to "Back", :back, class: "btn btn-primary" %>