config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  get 'logout', to: 'sessions#destroy'
  get 'bag', to: 'products#bag'
  get 'harness', to: 'products#harness'
  get '/auth/facebook/callback', to: 'sessions#omni'
  get '/auth/google_oauth2/callback', to: 'sessions#omni'
  
  resources :users
  resources :po_products
  resources :product_materials
  resources :materials
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :purchase_orders do 
    resources :po_products
  end
  
  resources :products do 
    resources :product_materials
  end
  


end

app/models/product_material.rb
class ProductMaterial < ApplicationRecord
  
  belongs_to :product
  belongs_to :material

  validates :quantity, presence: true
end

app/controllers/product_materials_controller.rb
class ProductMaterialsController < ApplicationController
    before_action :logged_in?
    before_action :set_product_material, only: [:show, :edit, :update, :destroy]
    before_action :edit_or_delete, only: [:edit, :update, :destroy]
       
    def index
        if params[:product_id] && @product = Product.find_by(id: params[:product_id])
            @product_materials = @product.product_materials
        else
            @product_materials = ProductMaterial.all
        end
    end

    def new
        @product_material = ProductMaterial.new(product_id: params[:product_id])
    end
    
    def create
        @product_material = ProductMaterial.new(pm_params)
        if @product_material.save!
            redirect_to materials_path
        else
            render :new
        end
    end

    def show 
    end

    def edit 
    end

    def update 
        if @product_material.update(pm_params)
            redirect_to purchase_order_po_products_path(@product_material)
        else 
            render :new
        end
    end

    def destroy
        @product_material.destroy 
        redirect_to product_product_materials_path(@product_material)
    end

    private 
    def pm_params
        params.require(:product_material).permit(:quantity, :product_id, :material_id)
    end

    def set_product_material
        @product_material = ProductMaterial.find_by(id: params[:id])
        if !@product_material
            redirect_to product_materials_path
        end
    end

    def edit_or_delete
        set_product_material
        redirect_to product_materials_path, alert: "Editing permissions denied" unless !!authorized
    end

    def authorized
        helpers.current_user == @product_material.product.user
     end
end

app/helpers/product_materials_helper.rb
module ProductMaterialsHelper
end

app/views/product_materials/_form.html.erb
<h3 class="login-heading mb-4">New Product Material</h3>
<%= render partial: 'shared/errors', locals: {model: @product_material} %>
<%= render partial: 'shared/flash_errors', locals: {model: @product_material} %>
<br>
<%= form_for @product_material do |f| %>
    <%= f.number_field :quantity, placeholder: "Quantity", required: true, class: "form-control", autofocus: true %><br>
    <%= f.collection_select :product_id, Product.all, :id, :name, prompt: "Product" %><br><br>
    <%= f.collection_select :material_id, Material.all, :id, :name, prompt: "Material" %>
    <hr>
    <% if current_page?(new_product_material_path) %>
        <%= f.button "Assign Material to Product", class: "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" %>
    <% else %>
        <%= f.button "Update Product Material", class: "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" %>
    <% end %>
    <hr>
    Didn't find product or material?
    <hr>
    <%= link_to "Create Product", new_product_path, class: "btn btn-primary" %>&nbsp;&nbsp;&nbsp; OR &nbsp;&nbsp;&nbsp;
    <%= link_to "Create Material", new_material_path, class: "btn btn-primary" %><hr>
    <%= link_to "Back", :back, class: "btn btn-primary" %>
<% end %>

app/views/product_materials/index.html.erb
<%= render partial: 'shared/flash_errors', locals: {model: @product_material} %>
<table>
    <tr>
        <th>Name</th>
        <th>Color</th>
        <th>Size</th>
        <th>SKU</th>
        <th>Category</th>
        <th>Quantity</th>
        <% @product_materials.each do |pm| %>
    </tr>
        <td><%= button_to pm.material.name, product_product_material_path(pm.product, pm), method: :get %></td>
        <td><%= pm.material.color %></td>
        <td><%= pm.material.size %></td>
        <td><%= pm.material.sku %></td>
        <td><%= pm.material.category %></td>
        <td><%= pm.quantity %></td>
    </tr>
        <% end %>
</table>
<hr>
<%= link_to "Back", :back, class: "btn btn-primary" %>

app/views/product_materials/new.html.erb
<%= render "form" %>

app/views/product_materials/show.html.erb
<h3 class="login-heading mb-4"><%= @product_material.material.try(:name) %></h3>
<%= render partial: 'shared/errors', locals: {model: @product_material} %>
<%= render partial: 'shared/flash_errors', locals: {model: @product_material} %>
<table>
    <tr>
        <th>Quantity</th>
    </tr>
        <td><%= @product_material.quantity %></td>
    </tr>
</table>
<hr>
<%= link_to "Edit", edit_product_material_path(@product_material), class: "btn btn-primary" %>&nbsp;&nbsp;&nbsp; OR &nbsp;&nbsp;&nbsp;
<%= link_to "Delete", product_material_path(@product_material), method: :delete, class: "btn btn-primary",data: {confirm: "Are you sure?"} %><hr>
<%= link_to "Back", :back, class: "btn btn-primary" %>