config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  get 'logout', to: 'sessions#destroy'
  get 'bag', to: 'products#bag'
  get 'harness', to: 'products#harness'
  get '/auth/facebook/callback', to: 'sessions#omni'
  get '/auth/google_oauth2/callback', to: 'sessions#omni'
  
  resources :users
  resources :po_products
  resources :product_materials
  resources :materials
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :purchase_orders do 
    resources :po_products
  end
  
  resources :products do 
    resources :product_materials
  end
  


end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user 
  has_many :po_products
  has_many :purchase_orders, through: :po_products
  has_many :product_materials
  has_many :materials, through: :product_materials
  
  validates :name, :color, :size, :sku, :category, presence: true
  validates :name, :sku, uniqueness: true

  scope :bag, -> {where(category: "bag")}  
  scope :harness, -> {where(category: "harness")}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :logged_in?
    before_action :set_product, only: [:show, :edit, :update, :destroy]
    before_action :edit_or_delete, only: [:edit, :update, :destroy]

    def index 
        @products = Product.all
    end

    def bag
        @products = Product.all.bag
    end

    def harness
        @products = Product.all.harness
    end

    def new 
        @product = Product.new
    end
    
    def create
        @product = helpers.current_user.products.build(product_params)
        if @product.save
            redirect_to products_path
        else 
            render :new
        end
    end

    def show 
    end

    def edit 
    end

    def update
        if @product.update(product_params)
            redirect_to product_path(@product)
        else
            render :new
        end
    end

    def destroy 
        @product.destroy 
        redirect_to products_path
    end

    private 
    def product_params
        params.require(:product).permit(:name, :color, :size, :sku, :category )
    end

    def set_product
        @product = Product.find_by(id: params[:id])
        if !@product
            redirect_to products_path
        end
    end

    def edit_or_delete
        set_product
        redirect_to products_path, alert: "Editing permissions denied" unless !!authorized
    end

    def authorized
        helpers.current_user == @product.user
     end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<h3 class="login-heading mb-4">New Product</h3>
<%= render partial: 'shared/errors', locals: {model: @product} %>
<%= render partial: 'shared/flash_errors', locals: {model: @product} %>

<br>
<%= form_for @product do |f| %>
    <%= f.text_field :name, placeholder: "Name", required: true, class: "form-control", autofocus: true %><br>
    <%= f.text_field :sku, placeholder: "SKU", required: true, class: "form-control" %><br>
    <%= f.select :color, ["coyote", "black", "multicam"], prompt: "Color" %><br><br>
    <%= f.select :category, ["bag", "harness", "accessory"], prompt: "Type"%><br><br>
    <%= f.select :size, ["xs", "s", "m", "m/l", "l", "xl", "xxl"], prompt: "Size" %><br><br>
    <%= link_to "Back", :back, class: "btn btn-primary" %>
    <hr>
    <%= f.button class: "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" %>
<% end %>
            

app/views/products/_products.html.erb
<%= render partial: 'shared/flash_errors', locals: {model: @product} %>

<table>
    <tr>
        <th>Name</th>
        <th>Color</th>
        <th>Size</th>
        <th>SKU</th>
        <th>Category</th>
        <% @products.each do |p| %>
    </tr>
        <td><%= button_to p.name, product_path(p), method: :get %></td>
        <td><%= p.color.titlecase %></td>
        <td><%= p.size.upcase %></td>
        <td><%= p.sku %></td>
        <td><%= p.category.titlecase %></td>
    </tr>
        <% end %>
</table>
<br>

app/views/products/bag.html.erb
<%= render 'products' %>
<%= link_to "Back", :back, class: "btn btn-primary" %>

app/views/products/harness.html.erb
<%= render 'products' %>
<%= link_to "Back", :back, class: "btn btn-primary" %>

app/views/products/index.html.erb
<h2 class="po-index-heading mb-4">All Products</h2>

<%= render "products" %>

<select onchange="window.location=this.value">
  <option>View by Type</option>
  <% @products.each do |p| %> 
    <option value="/<%= p.category %>"><%= p.category.titlecase %></option>
  <% end %>
</select><br><br>

<%= link_to "New Product", new_product_path, class: "btn btn-primary" %>&nbsp;&nbsp;&nbsp; OR &nbsp;&nbsp;&nbsp;
<%= link_to "Add Product to P.O.", new_po_product_path, class: "btn btn-primary" %><hr>
<%= link_to "Back", :back, class: "btn btn-primary" %>

app/views/products/show.html.erb
<table>
    <tr>
        <th>Name</th>
        <th>Color</th>
        <th>Size</th>
        <th>SKU</th>
        <th>Type</th>
    </tr>
        <td><%= @product.name.titleize %></td>
        <td><%= @product.color.titleize %></td>
        <td><%= @product.size.upcase %></td>
        <td><%= @product.sku %></td>
        <td><%= @product.category.titleize %></td>
    </tr>
</table>
<hr>
<%= link_to "More Info...", product_product_materials_path(@product), class: "btn btn-primary" %>&nbsp;&nbsp;&nbsp;
<%= link_to "Edit", edit_product_path(@product), class: "btn btn-primary" %>&nbsp;&nbsp;&nbsp;
<%= link_to "Delete", product_path(@product), method: :delete, class: "btn btn-primary",data: {confirm: "Are you sure?"} %><br><br>
<%= link_to "Add Product to Purchase Order", new_purchase_order_po_product_path(@product), class: "btn btn-primary" %><br><br>
<%= link_to "Add Material to Product", new_product_product_material_path(@product), class: "btn btn-primary" %><hr>
<%= link_to "Back", :back, class: "btn btn-primary" %>